# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 23:34
from __future__ import unicode_literals

import awesome_staff.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('max_players', awesome_staff.fields.IntegerRangeField(default=4)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
